PLATFORM-7963 Upgrade RedisCache
Wikia/RedisCache pull request #1
Opened 2023-01-30 11:56 UTC by slayful

2023-01-30 12:27 UTC, t-tomalak requested changes
One issue

2023-01-30 12:27 UTC, t-tomalak commented on src/RedisCache.php
> +	public function __construct( private array $redisServers, private LoggerInterface $logger ) { }
**issue**: I'm not sure if the `redisServer` is always declared. I can't see default configuration in variables-base.php, and only those for prod/dev, so sandbox, preview, verify may throw TypeError exception.

I don't know why it was declared like that (maybe to not override cache on staging/testing environments), but there are options like prefix etc. which probably should help with that. Tho not sure if we should change that behaviour right now

2023-01-30 12:50 UTC, t-tomalak requested changes

2023-01-30 12:50 UTC, t-tomalak commented on ServiceWiring.php
> +			$services->getMainConfig()->get( 'RedisServers' ),
**issue** This will throw exception on undefined config value eg. for preview verify etc.

2023-01-31 17:54 UTC, mszabo-wikia commented on src/RedisCache.php
> +		}
`MWException` just got deprecated (ref https://phabricator.wikimedia.org/T321683#8347775, https://phabricator.wikimedia.org/T86704), so we should use e.g. `Wikimedia\Assert` instead:
```php
Assert::precondition(
extension_loaded( 'redis' ),
__METHOD__ .
				" - The PHP Redis extension is not available.  Please enable it on the server to use RedisCache."
);
```

2023-02-08 10:47 UTC, mszabo-wikia approved these changes

2023-02-08 11:28 UTC, t-tomalak approved these changes

2023-02-08 11:30 UTC, merged